import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, renameSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';

function listFiles(dir: string, base = dir): string[] {
  return readdirSync(dir).flatMap((name) => {
    const full = path.join(dir, name);
    return statSync(full).isDirectory() ? listFiles(full, base) : [path.relative(base, full).split(path.sep).join('/')];
  });
}

/**
 * After a web build: serve web.html as index.html, and write sw.js, a
 * service worker that caches every built file so the app works offline.
 * The cache name is a hash of the build, so each deploy replaces the old cache.
 */
export default function webApp(outDir: string): Plugin {
  return {
    name: 'ctz-web-app',
    apply: 'build',
    closeBundle() {
      renameSync(path.join(outDir, 'web.html'), path.join(outDir, 'index.html'));

      const files = listFiles(outDir).filter((f) => f !== 'sw.js');
      const hash = createHash('sha256');
      for (const f of files.sort()) hash.update(f).update(readFileSync(path.join(outDir, f)));
      const version = hash.digest('hex').slice(0, 12);
      const precache = ['./', ...files.map((f) => `./${f}`)];

      const sw = `// Generated by web/vite-plugin-web.ts. Do not edit.
const CACHE = 'ctz-${version}';
const FILES = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('ctz-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // Page: network first so updates arrive, cached copy when offline.
    event.respondWith(fetch(req).catch(() => caches.match('./index.html')));
    return;
  }
  // Built files have hashed names, so a cached copy is always correct.
  event.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req)));
});
`;
      writeFileSync(path.join(outDir, 'sw.js'), sw);
    },
  };
}
